'use strict';

const DOMAIN_TICKERS = {

  // ── US Tech (Large Cap) ──────────────────────────────────────────
  'apple.com':               'AAPL',
  'microsoft.com':           'MSFT',
  'amazon.com':              'AMZN',
  'google.com':              'GOOGL',
  'alphabet.com':            'GOOGL',
  'meta.com':                'META',
  'facebook.com':            'META',
  'instagram.com':           'META',
  'whatsapp.com':            'META',
  'netflix.com':             'NFLX',
  'tesla.com':               'TSLA',
  'nvidia.com':              'NVDA',
  'intel.com':               'INTC',
  'amd.com':                 'AMD',
  'arm.com':                 'ARM',
  'broadcom.com':            'AVGO',
  'qualcomm.com':            'QCOM',
  'micron.com':              'MU',
  'westerndigital.com':      'WDC',
  'seagate.com':             'STX',
  'hp.com':                  'HPQ',
  'dell.com':                'DELL',

  // ── US Tech (Software / Cloud) ──────────────────────────────────
  'adobe.com':               'ADBE',
  'salesforce.com':          'CRM',
  'oracle.com':              'ORCL',
  'ibm.com':                 'IBM',
  'cisco.com':               'CSCO',
  'servicenow.com':          'NOW',
  'workday.com':             'WDAY',
  'intuit.com':              'INTU',
  'sap.com':                 'SAP.DE',
  'zoom.us':                 'ZM',
  'twilio.com':              'TWLO',
  'cloudflare.com':          'NET',
  'datadog.com':             'DDOG',
  'snowflake.com':           'SNOW',
  'mongodb.com':             'MDB',
  'elastic.co':              'ESTC',
  'confluent.com':           'CFLT',
  'digitalocean.com':        'DOCN',
  'fastly.com':              'FSLY',
  'akamai.com':              'AKAM',
  'okta.com':                'OKTA',
  'hubspot.com':             'HUBS',
  'zendesk.com':             'ZEN',
  'atlassian.com':           'TEAM',
  'gitlab.com':              'GTLB',
  'nutanix.com':             'NTNX',
  'veeva.com':               'VEEV',
  'paloaltonetworks.com':    'PANW',
  'crowdstrike.com':         'CRWD',
  'fortinet.com':            'FTNT',
  'zscaler.com':             'ZS',
  'splunk.com':              'SPLK',
  'unity.com':               'U',

  // ── US Tech (Consumer Internet) ─────────────────────────────────
  'spotify.com':             'SPOT',
  'uber.com':                'UBER',
  'lyft.com':                'LYFT',
  'airbnb.com':              'ABNB',
  'coinbase.com':            'COIN',
  'paypal.com':              'PYPL',
  'shopify.com':             'SHOP',
  'snap.com':                'SNAP',
  'dropbox.com':             'DBX',
  'palantir.com':            'PLTR',
  'roblox.com':              'RBLX',
  'robinhood.com':           'HOOD',
  'reddit.com':              'RDDT',
  'pinterest.com':           'PINS',
  'doordash.com':            'DASH',
  'ebay.com':                'EBAY',
  'etsy.com':                'ETSY',
  'wayfair.com':             'W',
  'chewy.com':               'CHWY',
  'match.com':               'MTCH',
  'tinder.com':              'MTCH',
  'block.com':               'SQ',
  'square.com':              'SQ',
  'stripe.com':              'STRP',

  // ── Gaming ───────────────────────────────────────────────────────
  'ea.com':                  'EA',
  'take-two.com':            'TTWO',
  'nintendo.com':            'NTDOY',
  'ubisoft.com':             'UBI.PA',

  // ── US Finance ───────────────────────────────────────────────────
  'visa.com':                'V',
  'mastercard.com':          'MA',
  'jpmorgan.com':            'JPM',
  'chase.com':               'JPM',
  'goldmansachs.com':        'GS',
  'morganstanley.com':       'MS',
  'bankofamerica.com':       'BAC',
  'wellsfargo.com':          'WFC',
  'citigroup.com':           'C',
  'citi.com':                'C',
  'blackrock.com':           'BLK',
  'americanexpress.com':     'AXP',
  'schwab.com':              'SCHW',
  'berkshirehathaway.com':   'BRK-B',
  'fidelity.com':            'FNF',
  'td.com':                  'TD',

  // ── US Consumer / Retail ─────────────────────────────────────────
  'walmart.com':             'WMT',
  'target.com':              'TGT',
  'costco.com':              'COST',
  'homedepot.com':           'HD',
  'lowes.com':               'LOW',
  'mcdonalds.com':           'MCD',
  'starbucks.com':           'SBUX',
  'chipotle.com':            'CMG',
  'yum.com':                 'YUM',
  'cocacola.com':            'KO',
  'coca-cola.com':           'KO',
  'pepsi.com':               'PEP',
  'pepsico.com':             'PEP',
  'mondelez.com':            'MDLZ',
  'kraftheinz.com':          'KHC',
  'generalmills.com':        'GIS',
  'nike.com':                'NKE',
  'lululemon.com':           'LULU',
  'gap.com':                 'GPS',
  'ralphlauren.com':         'RL',
  'procter.com':             'PG',
  'pg.com':                  'PG',
  'colgate.com':             'CL',
  'kimberly-clark.com':      'KMB',
  'hasbro.com':              'HAS',
  'mattel.com':              'MAT',

  // ── US Media / Telecom ───────────────────────────────────────────
  'disney.com':              'DIS',
  'wbd.com':                 'WBD',
  'warnerbros.com':          'WBD',
  'paramount.com':           'PARA',
  'fox.com':                 'FOX',
  'nytimes.com':             'NYT',
  'comcast.com':             'CMCSA',
  'charter.com':             'CHTR',
  'att.com':                 'T',
  't-mobile.com':            'TMUS',
  'verizon.com':             'VZ',

  // ── US Industrial / Aerospace / Defense ─────────────────────────
  'boeing.com':              'BA',
  'ge.com':                  'GE',
  'lockheedmartin.com':      'LMT',
  'rtx.com':                 'RTX',
  'raytheon.com':            'RTX',
  'northropgrumman.com':     'NOC',
  'generaldynamics.com':     'GD',
  'l3harris.com':            'LHX',
  'caterpillar.com':         'CAT',
  'deere.com':               'DE',
  '3m.com':                  'MMM',
  'honeywell.com':           'HON',
  'emerson.com':             'EMR',
  'parker.com':              'PH',

  // ── US Energy ────────────────────────────────────────────────────
  'exxonmobil.com':          'XOM',
  'chevron.com':             'CVX',
  'conocophillips.com':      'COP',
  'eog.com':                 'EOG',
  'nexteraenergy.com':       'NEE',
  'duke-energy.com':         'DUK',

  // ── US Auto ──────────────────────────────────────────────────────
  'ford.com':                'F',
  'gm.com':                  'GM',
  'rivian.com':              'RIVN',
  'lucidmotors.com':         'LCID',

  // ── US Healthcare / Pharma / Biotech ─────────────────────────────
  'unitedhealth.com':        'UNH',
  'uhc.com':                 'UNH',
  'elevancehealth.com':      'ELV',
  'cvs.com':                 'CVS',
  'pfizer.com':              'PFE',
  'abbvie.com':              'ABBV',
  'merck.com':               'MRK',
  'lilly.com':               'LLY',
  'modernatx.com':           'MRNA',
  'jnj.com':                 'JNJ',
  'amgen.com':               'AMGN',
  'gilead.com':              'GILD',
  'biogen.com':              'BIIB',
  'regeneron.com':           'REGN',
  'vertex.com':              'VRTX',
  'illumina.com':            'ILMN',
  'intuitive.com':           'ISRG',
  'medtronic.com':           'MDT',
  'stryker.com':             'SYK',

  // ── Swiss (SIX) ──────────────────────────────────────────────────
  'nestle.com':              'NESN.SW',
  'novartis.com':            'NOVN.SW',
  'roche.com':               'ROG.SW',
  'ubs.com':                 'UBSG.SW',
  'credit-suisse.com':       'UBSG.SW',
  'zurich.com':              'ZURN.SW',
  'swissre.com':             'SREN.SW',
  'lonza.com':               'LONN.SW',
  'sika.com':                'SIKA.SW',
  'abb.com':                 'ABBN.SW',
  'swisscom.ch':             'SCMN.SW',
  'givaudan.com':            'GIVN.SW',
  'partners-group.com':      'PGHN.SW',
  'juliusbaer.com':          'BAER.SW',
  'straumann.com':           'STMN.SW',
  'sonova.com':              'SOON.SW',
  'kuehne-nagel.com':        'KNIN.SW',
  'schindler.com':           'SCHN.SW',
  'richemont.com':           'CFR.SW',
  'swatch.com':              'UHRN.SW',
  'bachem.com':              'BCHN.SW',
  'ems-chemie.com':          'EMSN.SW',

  // ── German (XETRA) ───────────────────────────────────────────────
  'volkswagen.com':          'VOW3.DE',
  'bmw.com':                 'BMW.DE',
  'mercedes-benz.com':       'MBG.DE',
  'porsche.com':             'P911.DE',
  'audi.com':                'VOW3.DE',
  'siemens.com':             'SIE.DE',
  'siemens-energy.com':      'ENR.DE',
  'allianz.com':             'ALV.DE',
  'basf.com':                'BAS.DE',
  'adidas.com':              'ADS.DE',
  'puma.com':                'PUM.DE',
  'henkel.com':              'HEN.DE',
  'beiersdorf.com':          'BEI.DE',
  'bayer.com':               'BAYN.DE',
  'merck.de':                'MRK.DE',
  'fresenius.com':           'FRE.DE',
  'deutschebank.com':        'DBK.DE',
  'db.com':                  'DBK.DE',
  'commerzbank.com':         'CBK.DE',
  'dhl.com':                 'DHL.DE',
  'lufthansa.com':           'LHA.DE',
  'fraport.com':             'FRA.DE',
  'continental.com':         'CON.DE',
  'rheinmetall.com':         'RHM.DE',
  'munich-re.com':           'MUV2.DE',
  'rwe.com':                 'RWE.DE',
  'eon.com':                 'EOAN.DE',
  'evonik.com':              'EVK.DE',

  // ── French (Euronext Paris) ──────────────────────────────────────
  'lvmh.com':                'MC.PA',
  'hermes.com':              'RMS.PA',
  'kering.com':              'KER.PA',
  'loreal.com':              'OR.PA',
  'sanofi.com':              'SAN.PA',
  'totalenergies.com':       'TTE.PA',
  'airbus.com':              'AIR.PA',
  'schneider-electric.com':  'SU.PA',
  'essilorluxottica.com':    'EL.PA',
  'dassault-systemes.com':   'DSY.PA',
  'capgemini.com':           'CAP.PA',
  'bnpparibas.com':          'BNP.PA',
  'societegenerale.com':     'GLE.PA',
  'credit-agricole.com':     'ACA.PA',
  'axa.com':                 'CS.PA',
  'danone.com':              'BN.PA',
  'pernod-ricard.com':       'RI.PA',
  'michelin.com':            'ML.PA',
  'renault.com':             'RNO.PA',
  'stellantis.com':          'STLAM.MI',
  'saint-gobain.com':        'SGO.PA',
  'vinci.com':               'DG.PA',
  'orange.com':              'ORA.PA',
  'vivendi.com':             'VIV.PA',
  'ubisoft.com':             'UBI.PA',
  'accorhotels.com':         'AC.PA',

  // ── Dutch (Euronext Amsterdam) ───────────────────────────────────
  'asml.com':                'ASML.AS',
  'shell.com':               'SHEL.AS',
  'ing.com':                 'INGA.AS',
  'abn-amro.com':            'ABN.AS',
  'heineken.com':            'HEIA.AS',
  'unilever.com':            'ULVR.L',
  'philips.com':             'PHIA.AS',
  'wolterskluwer.com':       'WKL.AS',

  // ── UK (London Stock Exchange) ───────────────────────────────────
  'bp.com':                  'BP.L',
  'astrazeneca.com':         'AZN.L',
  'gsk.com':                 'GSK.L',
  'glaxosmithkline.com':     'GSK.L',
  'hsbc.com':                'HSBA.L',
  'barclays.com':            'BARC.L',
  'lloyds.com':              'LLOY.L',
  'natwest.com':             'NWG.L',
  'standardchartered.com':   'STAN.L',
  'vodafone.com':            'VOD.L',
  'bt.com':                  'BT-A.L',
  'rolls-royce.com':         'RR.L',
  'baesystems.com':          'BA.L',
  'diageo.com':              'DGE.L',
  'burberry.com':            'BRBY.L',
  'tesco.com':               'TSCO.L',
  'reckitt.com':             'RKT.L',
  'riotinto.com':            'RIO.L',
  'bhp.com':                 'BHP.L',

  // ── Italian (Borsa Italiana) ─────────────────────────────────────
  'eni.com':                 'ENI.MI',
  'enel.com':                'ENEL.MI',
  'intesasanpaolo.com':      'ISP.MI',
  'unicredit.com':           'UCG.MI',
  'ferrari.com':             'RACE',
  'moncler.com':             'MONC.MI',
  'prysmian.com':            'PRY.MI',
  'leonardo.com':            'LDO.MI',

  // ── Spanish (BME) ────────────────────────────────────────────────
  'santander.com':           'SAN.MC',
  'bbva.com':                'BBVA.MC',
  'telefonica.com':          'TEF.MC',
  'inditex.com':             'ITX.MC',
  'zara.com':                'ITX.MC',
  'iberdrola.com':           'IBE.MC',
  'repsol.com':              'REP.MC',

  // ── Nordic ───────────────────────────────────────────────────────
  'volvo.com':               'VOLV-B.ST',
  'h-m.com':                 'HMB.ST',
  'ericsson.com':            'ERIC',
  'nokia.com':               'NOKIA.HE',
  'equinor.com':             'EQNR',

  // ── Asian ────────────────────────────────────────────────────────
  'samsung.com':             'SSNLF',
  'sony.com':                'SONY',
  'toyota.com':              'TM',
  'honda.com':               'HMC',
  'nissan.com':              'NSANY',
  'hyundai.com':             'HYMTF',
  'lg.com':                  'LGEIY',
  'alibaba.com':             'BABA',
  'jd.com':                  'JD',
  'baidu.com':               'BIDU',
  'tencent.com':             'TCEHY',
  'tsmc.com':                'TSM',
  'softbank.com':            'SFTBY',
  'nio.com':                 'NIO',
  'xiaomi.com':              'XIACY',
};
