'use strict';

const DOMAIN_TICKERS = {
  // US Tech
  'apple.com':          'AAPL',
  'microsoft.com':      'MSFT',
  'amazon.com':         'AMZN',
  'google.com':         'GOOGL',
  'alphabet.com':       'GOOGL',
  'meta.com':           'META',
  'facebook.com':       'META',
  'instagram.com':      'META',
  'netflix.com':        'NFLX',
  'tesla.com':          'TSLA',
  'nvidia.com':         'NVDA',
  'intel.com':          'INTC',
  'amd.com':            'AMD',
  'qualcomm.com':       'QCOM',
  'adobe.com':          'ADBE',
  'salesforce.com':     'CRM',
  'oracle.com':         'ORCL',
  'ibm.com':            'IBM',
  'cisco.com':          'CSCO',
  'spotify.com':        'SPOT',
  'uber.com':           'UBER',
  'lyft.com':           'LYFT',
  'airbnb.com':         'ABNB',
  'coinbase.com':       'COIN',
  'paypal.com':         'PYPL',
  'shopify.com':        'SHOP',
  'zoom.us':            'ZM',
  'snap.com':           'SNAP',
  'dropbox.com':        'DBX',
  'cloudflare.com':     'NET',
  'datadog.com':        'DDOG',
  'snowflake.com':      'SNOW',
  'palantir.com':       'PLTR',
  'roblox.com':         'RBLX',
  'robinhood.com':      'HOOD',
  'twilio.com':         'TWLO',
  'servicenow.com':     'NOW',
  'workday.com':        'WDAY',
  'intuit.com':         'INTU',

  // Finance
  'visa.com':           'V',
  'mastercard.com':     'MA',
  'jpmorgan.com':       'JPM',
  'chase.com':          'JPM',
  'goldmansachs.com':   'GS',
  'morganstanley.com':  'MS',
  'bankofamerica.com':  'BAC',
  'wellsfargo.com':     'WFC',
  'blackrock.com':      'BLK',
  'americanexpress.com':'AXP',
  'schwab.com':         'SCHW',

  // Consumer / Retail
  'walmart.com':        'WMT',
  'target.com':         'TGT',
  'costco.com':         'COST',
  'homedepot.com':      'HD',
  'mcdonalds.com':      'MCD',
  'starbucks.com':      'SBUX',
  'cocacola.com':       'KO',
  'coca-cola.com':      'KO',
  'pepsi.com':          'PEP',
  'pepsico.com':        'PEP',
  'nike.com':           'NKE',
  'adidas.com':         'ADDYY',
  'ikea.com':           'N/A',
  'zara.com':           'ITX.MC',
  'lvmh.com':           'LVMUY',

  // Media / Telecom
  'disney.com':         'DIS',
  'comcast.com':        'CMCSA',
  'att.com':            'T',
  't-mobile.com':       'TMUS',
  'verizon.com':        'VZ',
  'spotify.com':        'SPOT',

  // Industrial / Energy
  'boeing.com':         'BA',
  'ge.com':             'GE',
  'exxonmobil.com':     'XOM',
  'chevron.com':        'CVX',
  'shell.com':          'SHEL',
  'bp.com':             'BP',
  'siemens.com':        'SIEGY',
  'abb.com':            'ABB',

  // Healthcare / Pharma
  'pfizer.com':         'PFE',
  'abbvie.com':         'ABBV',
  'merck.com':          'MRK',
  'lilly.com':          'LLY',
  'novartis.com':       'NVS',
  'roche.com':          'RHHBY',
  'biontech.de':        'BNTX',
  'modernatx.com':      'MRNA',
  'jnj.com':            'JNJ',

  // Swiss
  'nestle.com':         'NSRGY',
  'ubs.com':            'UBS',
  'zurich.com':         'ZURVY',
  'lonza.com':          'LZAGY',
  'sika.com':           'SXYAY',
  'swisscom.ch':        'SCMWY',
  'credit-suisse.com':  'UBS',

  // European
  'volkswagen.com':     'VWAGY',
  'bmw.com':            'BMWYY',
  'mercedes-benz.com':  'MBGYY',
  'sap.com':            'SAP',
  'asml.com':           'ASML',
  'totalenergies.com':  'TTE',
  'airbus.com':         'EADSY',
  'allianz.com':        'ALIZY',
  'basf.com':           'BASFY',

  // Asian
  'samsung.com':        'SSNLF',
  'sony.com':           'SONY',
  'toyota.com':         'TM',
  'honda.com':          'HMC',
  'alibaba.com':        'BABA',
  'tsmc.com':           'TSM',
};
